<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <DefaultNamespace>Kokoabim.BinaryCookiesToJson</DefaultNamespace>
        <AssemblyName>bc2j</AssemblyName>
        <AssemblyVersion>1.2.1</AssemblyVersion>
        <FileVersion>1.2.1</FileVersion>
        <InformationalVersion>1.2.1</InformationalVersion>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\lib\Kokoabim.CommandLineInterface\src\Kokoabim.CommandLineInterface\Kokoabim.CommandLineInterface.csproj" />
    </ItemGroup>

</Project>
